# Generated by Django 5.1.2 on 2024-11-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='Junior', max_length=20)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
