# Generated by Django 5.1.3 on 2024-11-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='загрузите картинку')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название книги')),
                ('description', models.TextField(default='Lorem Ipsum', null=True, verbose_name='Напишите описание книги')),
                ('price', models.FloatField(verbose_name='Укажите цену книги')),
                ('genre', models.CharField(choices=[('Приключения', 'Приключения'), ('Книга рецептов', 'Книга рецептов'), ('Фентези', 'Фентези')], default='Комедия', max_length=100, verbose_name='Укажите жанр книги')),
                ('pages', models.TimeField(verbose_name='Укажите количество страниц в книге')),
                ('autor', models.CharField(max_length=30, verbose_name='Укажите автора книги')),
                ('audio_book', models.URLField(verbose_name='Укажите ссылку на аудио-книгу')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
