# Generated by Django 5.1.3 on 2024-11-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_books_delete_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.CharField(max_length=100, verbose_name='Укажите количество страниц в книге'),
        ),
    ]
