# Generated by Django 5.1.3 on 2024-11-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_books_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Приключения', 'Приключения'), ('Книга рецептов', 'Книга рецептов'), ('Фентези', 'Фентези')], default='Приключения', max_length=100, verbose_name='Укажите жанр книги'),
        ),
    ]
