# Generated by Django 5.1.2 on 2024-11-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_books_pages_reviewbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbooks',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
