# Generated by Django 5.1.2 on 2024-11-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_reviewbooks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Приключения', 'Приключения'), ('Книга рецептов', 'Книга рецептов'), ('Фентези', 'Фентези'), ('Современная проза', 'Современная проза'), ('Фантастика', 'Фантастика')], default='Приключения', max_length=100, verbose_name='Укажите жанр книги'),
        ),
    ]
