# Generated by Django 5.1.2 on 2024-11-29 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdevice',
            old_name='review_books',
            new_name='reviews_device',
        ),
        migrations.AlterField(
            model_name='reviewdevice',
            name='description',
            field=models.TextField(verbose_name='Оставьте отзыв о фильме'),
        ),
        migrations.AlterField(
            model_name='reviewdevice',
            name='mark',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Укажите оценку от 1 до 5'),
        ),
    ]
