# Generated by Django 5.1.2 on 2024-11-29 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_devices', '0002_rename_review_books_reviewdevice_reviews_device_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewdevice',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.RemoveField(
            model_name='reviewdevice',
            name='reviews_device',
        ),
        migrations.AddField(
            model_name='reviewdevice',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mobile_devices.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_of_purchase',
            field=models.DateField(null=True, verbose_name='Date of Purchase'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.FloatField(null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='reviewdevice',
            name='description',
            field=models.TextField(null=True, verbose_name='Leave a review for the device'),
        ),
        migrations.AlterField(
            model_name='reviewdevice',
            name='mark',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rate the device from 1 to 5'),
        ),
    ]
